name: Cancel

on: [push]

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest

    timeout-minutes: 2

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: release
          access_token: ${{ github.token }}
